name = "Coder Portfolio"
license = "MIT"
licenselink = "https://github.com/LEEHyeoksu/myweb/master/LICENSE.md"
description = "It is a theme to have you know yourself than developed based on hugo-coder"
homepage = "https://github.com/LEEHyeoksu/myweb"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.32"

[author]
  name = "Hyeoksu Lee"
  homepage = "https://leehyeoksu.github.io"

[original]
  author = "Luiz F. A. de Prá"
  homepage = "https://luizdepra.com"
  repo = "https://github.com/luizdepra/hugo-coder"